# Generated by Django 4.0.2 on 2022-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='type',
            field=models.CharField(choices=[('APP_ADMIN', 'App Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
    ]
